spring:
  application:
    name: employee-tree

---
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

---
spring:
  profiles: integration

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

---
spring:
  profiles: docker

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    hostname: localhost
